[package]
name = "network-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
serde = "1.0.217"
serde_json = "1.0.138"
speedtest-rs = "0.2.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3"
